In [3]:
import pandas as pd
import numpy as np


def test_run():
    '''
    '''

    # specifying the datatype
    arr = np.ones((5, 4), dtype=int)
    
    print(arr)
    
if __name__ == "__main__":
    test_run()


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# Create Random Array

In [6]:
help(np.random.random)

Help on built-in function random_sample:

random_sample(...) method of mtrand.RandomState instance
    random_sample(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random_sample` by `(b-a)` and add `a`::
    
      (b - a) * random_sample() + a
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    out : float or ndarray of floats
        Array of random floats of shape `size` (unless ``size=None``, in which
        case a single float is returned).
    
    Examples
    --------
    >>> np.random.random_sample()
    0.47108547995356098
    >>> type(np.random.random_

In [8]:
def test_random():
    '''
    Generate array of random values
    '''
    
    arr = np.random.random((5,4))
    
    # display array
    print(arr)
    
if __name__=="__main__":
    test_random()
    

    

[[0.03866095 0.98331436 0.80438338 0.39215877]
 [0.27836044 0.54342996 0.56213887 0.40606153]
 [0.30564632 0.53015671 0.07433171 0.68220326]
 [0.55190073 0.98275551 0.3095081  0.58724497]
 [0.870737   0.66301254 0.17142877 0.14492408]]


# Pass in a random normal distribution

In [11]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

In [15]:
def test_random_normal(rows,cols):
    '''
    Generate array of random values from the normal distribution
    '''
    # give mean of 50 and std dev of 10
    # loc = mean, scale = std dev
    arr = np.random.normal(loc=50, scale=10, size=(rows,cols))
    
    # display array
    print(arr)
    
if __name__=="__main__":
    test_random_normal(2,3)
    

[[47.59992325 54.0650407  51.54537361]
 [39.31133556 53.93669683 54.85871274]]


# Create Random Integers

In [18]:
help(np.random.randint)    

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i

In [25]:
def test_random_integers(min, max, size:tuple):
    '''
    Generate array of randomintegers
    '''
    arr = np.random.randint(low=min, high=max, size=size)
    
    # display array
    print(arr)
    
    return arr
    
if __name__=="__main__":
    test_random_integers(0, 10, (5,2))
    

[[1 5]
 [6 3]
 [1 2]
 [3 5]
 [5 5]]


# NumPy Shape

How to use the shape attribute

In [29]:
# get random shape arr

arr = test_random_integers(0, 10, (5,2))

print('The shape of the array is {}'.format(arr.shape))

[[2 8]
 [5 9]
 [7 4]
 [6 1]
 [4 2]]
The shape of the array is (5, 2)


Return the number of rows and columns of the shape

In [30]:
print('Total rows of array: {}'.format(arr.shape[0]))

print('Total columns of array:{}'.format(arr.shape[1]))


Total rows of array: 5
Total columns of array:2


Get the dimensions of the array

In [31]:
print('The dimensions of the array are: {}'.format(len(arr.shape)))

The dimensions of the array are: 2


Get the total number of elements present in the array

In [32]:
print('The total number of elements in the array is {}'.format(arr.size))

The total number of elements in the array is 10


Check the data type of the array

In [33]:
print('The data type of the array is {}'.format(arr.dtype))

The data type of the array is int32


# Operations on ndarrays

Sum all the values of the array

In [35]:
print('Sum of all elements = {}'.format(arr.sum()))


Sum of all elements = 48


In [38]:
print(arr)

[[2 8]
 [5 9]
 [7 4]
 [6 1]
 [4 2]]


Sum each axis.  Note that axis=0=rows; access=1=columns

In [36]:
print('The sum of the rows = {}'.format(arr.sum(axis=0)))

The sum of the rows = [24 24]


In [37]:
print('The sum of the columns = {}'.format(arr.sum(axis=1)))

The sum of the columns = [10 14 11  7  6]
